const VANCOUVER_CAT = "Vancouver Landmarks";
const THINGS_CAT = "Things";
const TRICKY_CAT = "Tricky Questions";
const CATCHY_CAT = "Catchy Things";
const ANIMAL_CAT = "Animals";
const COUNTRY_CAT = "Country Siluettes";
const FOOD_CAT = "Food";

export const questions = [
  {
    id: 1,
    category: VANCOUVER_CAT,
    difficulty: 1,
    question: "What is this Vancouver landmark?",
    answer: "Canada Place",
    answerImage: "vancouver_landmarks/a-canadap-1.jpg",
    image: "vancouver_landmarks/q-canadap-1.png",
  },
  {
    id: 2,
    category: VANCOUVER_CAT,
    difficulty: 1,
    question: "What is this Vancouver landmark?",
    answer: "East Van Sign",
    answerImage: "vancouver_landmarks/a-eastvan-1.jpg",
    image: "vancouver_landmarks/q-eastvan-1.png",
  },
  {
    id: 3,
    category: VANCOUVER_CAT,
    difficulty: 1,
    question: "What is this Vancouver landmark?",
    answer: "Arthur Erickson Place",
    answerImage: "vancouver_landmarks/a-macmillan-1.jpg",
    image: "vancouver_landmarks/q-macmillan-1.png",
  },
  {
    id: 4,
    category: VANCOUVER_CAT,
    difficulty: 1,
    question: "What is this Vancouver landmark?",
    answer: "Totem Poles in Stanley Park",
    answerImage: "vancouver_landmarks/a-totem-1.jpg",
    image: "vancouver_landmarks/q-totem-1.png",
  },
  {
    id: 5,
    category: VANCOUVER_CAT,
    difficulty: 2,
    question: "What is this Vancouver landmark?",
    answer: "BC Place",
    answerImage: "vancouver_landmarks/a-bcplace-2.jpg",
    image: "vancouver_landmarks/q-bcplace-2.png",
  },
  {
    id: 6,
    category: VANCOUVER_CAT,
    difficulty: 2,
    question: "What is this Vancouver landmark?",
    answer: "Marine Building",
    answerImage: "vancouver_landmarks/a-marine-2.jpg",
    image: "vancouver_landmarks/q-marine-2.png",
  },
  {
    id: 7,
    category: VANCOUVER_CAT,
    difficulty: 2,
    question: "What is this Vancouver landmark?",
    answer: "SFU Campus",
    answerImage: "vancouver_landmarks/a-sfu-2.jpg",
    image: "vancouver_landmarks/q-sfu-2.png",
  },
  {
    id: 8,
    category: VANCOUVER_CAT,
    difficulty: 2,
    question: "What is this Vancouver landmark?",
    answer: "Vancouver House",
    answerImage: "vancouver_landmarks/a-vhouse-2.jpg",
    image: "vancouver_landmarks/q-vhouse-2.png",
  },
  {
    id: 9,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Burrard Bridge",
    answerImage: "vancouver_landmarks/a-burrard-3.jpg",
    image: "vancouver_landmarks/q-burrard-3.png",
  },
  {
    id: 10,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Steam Clock in Gas Town",
    answerImage: "vancouver_landmarks/a-clock-3.jpg",
    image: "vancouver_landmarks/q-clock-3.png",
  },
  {
    id: 11,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Science World",
    answerImage: "vancouver_landmarks/a-sciencew-3.jpg",
    image: "vancouver_landmarks/q-sciencew-3.png",
  },
  {
    id: 12,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Museum of Anthropology",
    answerImage: "vancouver_landmarks/a-moa-3.jpeg",
    image: "vancouver_landmarks/q-moa-3.png",
  },
  {
    id: 13,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Sun Tower",
    answerImage: "vancouver_landmarks/a-suntower-3.jpg",
    image: "vancouver_landmarks/q-suntower-3.png",
  },
  {
    id: 14,
    category: THINGS_CAT,
    difficulty: 1,
    question: "What is this thing?",
    answer: "Mushroom",
    answerImage: "things/mushroom-1a.jpg",
    image: "things/mushroom-1q.png",
  },
  {
    id: 15,
    category: THINGS_CAT,
    difficulty: 1,
    question: "What is this thing?",
    answer: "Basketball hoop",
    answerImage: "things/net-1a.jpg",
    image: "things/net-1q.png",
  },
  {
    id: 16,
    category: THINGS_CAT,
    difficulty: 1,
    question: "What is this thing?",
    answer: "Pineapple",
    answerImage: "things/pineapple-1a.jpg",
    image: "things/pineapple-1q.png",
  },
  {
    id: 17,
    category: THINGS_CAT,
    difficulty: 1,
    question: "What is this thing?",
    answer: "Tire",
    answerImage: "things/tire-1a.png",
    image: "things/tire-1q.png",
  },
  {
    id: 18,
    category: THINGS_CAT,
    difficulty: 2,
    question: "What is this thing?",
    answer: "Battery",
    answerImage: "things/battery-2a.jpg",
    image: "things/battery-2q.png",
  },
  {
    id: 19,
    category: THINGS_CAT,
    difficulty: 2,
    question: "What is this thing?",
    answer: "Bowling ball",
    answerImage: "things/bowling-2a.jpg",
    image: "things/bowling-2q.png",
  },
  {
    id: 20,
    category: THINGS_CAT,
    difficulty: 2,
    question: "What is this thing?",
    answer: "$1 Coin",
    answerImage: "things/coin-2a.jpg.webp",
    image: "things/coin-2q.png",
  },
  {
    id: 21,
    category: THINGS_CAT,
    difficulty: 2,
    question: "What is this thing?",
    answer: "Piano",
    answerImage: "things/piano-2a.jpg",
    image: "things/piano-2q.png",
  },
  {
    id: 22,
    category: THINGS_CAT,
    difficulty: 3,
    question: "What is this thing?",
    answer: "Coffee cup",
    answerImage: "things/coffee-3a.jpg",
    image: "things/coffee-3q.png",
  },
  {
    id: 23,
    category: THINGS_CAT,
    difficulty: 3,
    question: "What is this thing?",
    answer: "MacBook or Apple Logo",
    answerImage: "things/macbook-3a.jpg",
    image: "things/macbook-3q.png",
  },
  {
    id: 24,
    category: THINGS_CAT,
    difficulty: 3,
    question: "What is this thing?",
    answer: "Coke can",
    answerImage: "things/coke-3a.png.webp",
    image: "things/coke-3q.png",
  },
  {
    id: 25,
    category: THINGS_CAT,
    difficulty: 3,
    question: "What is this thing?",
    answer: "Dandylion",
    answerImage: "things/dandylion-3a.jpeg",
    image: "things/dandylion-3q.png",
  },
  {
    id: 26,
    category: TRICKY_CAT,
    difficulty: 3,
    question: "What is always in front of you but can't be seen?",
    answer: "The future.",
  },
  {
    id: 27,
    category: TRICKY_CAT,
    difficulty: 2,
    question: "What has a neck but no head, two arms but no hands?",
    answer: "A shirt.",
  },
  {
    id: 28,
    category: TRICKY_CAT,
    difficulty: 3,
    question:
      "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?",
    answer: "A pencil.",
  },
  {
    id: 29,
    category: TRICKY_CAT,
    difficulty: 3,
    question:
      "I am light as a feather, yet the strongest one cannot hold me for long. What am I?",
    answer: "Breath.",
  },
  {
    id: 30,
    category: TRICKY_CAT,
    difficulty: 1,
    question: "The more you take, the more you leave behind. What am I?",
    answer: "Footsteps.",
  },
  {
    id: 31,
    category: TRICKY_CAT,
    difficulty: 1,
    question:
      "I am always hungry, I must always be fed, the finger I touch, will soon turn red. What am I?",
    answer: "Fire.",
  },
  {
    id: 32,
    category: TRICKY_CAT,
    difficulty: 2,
    question: "What has a head and a tail, but no body?",
    answer: "A coin.",
  },
  {
    id: 33,
    category: TRICKY_CAT,
    difficulty: 1,
    question:
      "I am an odd number. Take away a letter and I become even. What number am I?",
    answer: "Seven.",
  },
  {
    id: 34,
    category: TRICKY_CAT,
    difficulty: 2,
    question: "I can be cracked, made, told, and played. What am I?",
    answer: "A joke.",
  },
  {
    id: 35,
    category: CATCHY_CAT,
    difficulty: 1,
    question: `"D'oh!" is the catchphrase of which character?`,
    answer: "Homer Simpson",
  },
  {
    id: 36,
    category: CATCHY_CAT,
    difficulty: 2,
    question: `"What the deuce?" is the catchphrase of which character?`,
    answer: "Stewie Griffin",
  },
  {
    id: 37,
    category: CATCHY_CAT,
    difficulty: 1,
    question: `"Wubba lubba dub dub!" is the catchphrase of which character?`,
    answer: "Rick Sanchez",
  },
  {
    id: 38,
    category: CATCHY_CAT,
    difficulty: 3,
    question: `"Respect my authoritah!" is the catchphrase of which character?`,
    answer: "Eric Cartman",
  },
  {
    id: 39,
    category: CATCHY_CAT,
    difficulty: 2,
    question: `"Eat my shorts!" is the catchphrase of which character?`,
    answer: "Bart Simpson",
  },
  {
    id: 40,
    category: CATCHY_CAT,
    difficulty: 1,
    question: `"Giggity!" is the catchphrase of which character?`,
    answer: "Glenn Quagmire",
  },
  {
    id: 41,
    category: CATCHY_CAT,
    difficulty: 1,
    question:
      `"I turned myself into a pickle!" is a line from which character?`,
    answer: "Rick Sanchez",
  },
  {
    id: 42,
    category: CATCHY_CAT,
    difficulty: 2,
    question:
      `"Screw you guys, I'm going home!" is the catchphrase of which character?`,
    answer: "Eric Cartman",
  },
  {
    id: 43,
    category: CATCHY_CAT,
    difficulty: 3,
    question: `"What's up, doc?" is the catchphrase of which character?`,
    answer: "Bugs Bunny",
  },
  {
    id: 44,
    category: CATCHY_CAT,
    difficulty: 2,
    question: `"Oh, boy!" is the catchphrase of which character?`,
    answer: "Mickey Mouse",
  },
  {
    id: 45,
    category: CATCHY_CAT,
    difficulty: 3,
    question: `"Cowabunga!" is the catchphrase of which character?`,
    answer: "Michelangelo",
  },
  {
    id: 46,
    category: CATCHY_CAT,
    difficulty: 3,
    question: `"Aye carumba!" is the catchphrase of which character?`,
    answer: "Bart Simpson",
  },
  {
    id: 47,
    category: ANIMAL_CAT,
    difficulty: 2,
    question: "Helminthology is the study of which creature?",
    answer: "Parasitic Worm",
    choices: ["Badger", "Mole", "Parasitic Worm", "Centipede"],
  },
  {
    id: 48,
    category: ANIMAL_CAT,
    difficulty: 1,
    question:
      "What is the only fruit in which the seeds grow on the outside of its skin?",
    answer: "Strawberry",
    choices: ["Kumquat", "Bilberry", "Strawberry", "Gooseberry"],
  },
  {
    id: 49,
    category: ANIMAL_CAT,
    difficulty: 2,
    question: "What color is the tongue of a giraffe?",
    answer: "Black",
    choices: ["Red", "Yellow", "Green", "Black"],
  },
  {
    id: 50,
    category: ANIMAL_CAT,
    difficulty: 3,
    question: "What is the collective name for a group of frogs?",
    answer: "Army",
    choices: ["Army", "Herd", "Legion", "Tribe"],
  },
  {
    id: 51,
    category: ANIMAL_CAT,
    difficulty: 3,
    question: "The bark of which tree was originally used to make aspirin?",
    answer: "Willow",
    choices: ["Redwood", "Birch", "Oak", "Willow"],
  },
  {
    id: 52,
    category: ANIMAL_CAT,
    difficulty: 3,
    question: "Trumpeter, Whooper and Mute are species of which type of bird?",
    answer: "Swan",
    choices: ["Duck", "Ostrich", "Swan", "Penguin"],
  },
  {
    id: 53,
    category: ANIMAL_CAT,
    difficulty: 1,
    question: "The leaves of which tree are the staple diet of the koala?",
    answer: "Eucalyptus",
    choices: ["Banksia", "Eucalyptus", "Golden Wattle", "Moreton Bay Fig"],
  },
  {
    id: 54,
    category: ANIMAL_CAT,
    difficulty: 2,
    question: "Which of the following animals is not a marsupial?",
    answer: "Platypus",
    choices: ["Platypus", "Wombat", "Opossum", "Bandicoot"],
  },
  {
    id: 55,
    category: ANIMAL_CAT,
    difficulty: 2,
    question:
      "With no internal or external skeleton, how many hearts does an octopus have?",
    answer: "Three",
    choices: ["Two", "None", "One", "Three"],
  },
  {
    id: 56,
    category: ANIMAL_CAT,
    difficulty: 1,
    question: "What colour are flamingos when they are born?",
    answer: "Grey",
    choices: ["White", "Blue", "Grey", "Pink"],
  },
  {
    id: 57,
    category: ANIMAL_CAT,
    difficulty: 1,
    question: "What is an infant seal called?",
    answer: "Pup",
    choices: ["Calf", "Cub", "Babe", "Pup"],
  },
  {
    id: 59,
    category: ANIMAL_CAT,
    difficulty: 2,
    question:
      "The extinct flightless bird 'dodo' was principally native to which island?",
    answer: "Mauritius",
    choices: ["Tasmania", "Zanzibar", "Madagascar", "Mauritius"],
  },

  {
    id: 60,
    category: ANIMAL_CAT,
    difficulty: 2,
    question: 'A "Lepidopterist" is someone who studies which type of animal?',
    answer: "Butterflies",
    choices: ["Butterflies", "Fish", "Ants", "Birds"],
  },
  {
    id: 61,
    category: COUNTRY_CAT,
    difficulty: 1,
    question: "Which country is it?",
    answer: "Russia",
    image: "countries/1-russia.png",
  },
  {
    id: 62,
    category: COUNTRY_CAT,
    difficulty: 1,
    question: "Which country is it?",
    answer: "Japan",
    image: "countries/1-japan.jpg",
  },
  {
    id: 63,
    category: COUNTRY_CAT,
    difficulty: 2,
    question: "Which country is it?",
    answer: "Denmark",
    image: "countries/2-denmark.jpg",
  },
  {
    id: 64,
    category: COUNTRY_CAT,
    difficulty: 2,
    question: "Which country is it?",
    answer: "Turkey",
    image: "countries/2-turkey.png",
  },
  {
    id: 65,
    category: COUNTRY_CAT,
    difficulty: 2,
    question: "Which country is it?",
    answer: "Croatia",
    image: "countries/2-croatia.png",
  },
  {
    id: 66,
    category: COUNTRY_CAT,
    difficulty: 2,
    question: "Which country is it?",
    answer: "Iceland",
    image: "countries/2-iceland.png",
  },
  {
    id: 67,
    category: COUNTRY_CAT,
    difficulty: 2,
    question: "Which country is it?",
    answer: "Norway",
    image: "countries/2-norway.png",
  },
  {
    id: 68,
    category: COUNTRY_CAT,
    difficulty: 3,
    question: "Which country is it?",
    answer: "Thailand",
    image: "countries/3-thailand.png",
  },
  {
    id: 69,
    category: COUNTRY_CAT,
    difficulty: 3,
    question: "Which country is it?",
    answer: "Egypt",
    image: "countries/3-egypt.png",
  },
  {
    id: 70,
    category: COUNTRY_CAT,
    difficulty: 3,
    question: "Which country is it?",
    answer: "South Korea",
    image: "countries/3-south-korea.jpg.webp",
  },
  {
    id: 71,
    category: COUNTRY_CAT,
    difficulty: 3,
    question: "Which country is it?",
    answer: "The Philippines",
    image: "countries/3-philippines.jpg",
  },
  {
    id: 72,
    category: FOOD_CAT,
    difficulty: 1,
    question:
      "What popular two-word Thai dish, served as either street food or a staple of Thai restaurants, is typically made with rice noodles, scrambled egg, peanuts, and meat, among other items?",
    answer: "Pad Thai",
  },
  {
    id: 73,
    category: FOOD_CAT,
    difficulty: 1,
    question:
      "Pizza Margherita is a typical Neapolitan pizza made with tomatoes, mozzarella cheese, salt, extra-virgin olive oil, and what culinary herb?",
    answer: "Basil",
  },
  {
    id: 74,
    category: FOOD_CAT,
    difficulty: 1,
    question:
      "One of Andy Warhol's most famous artworks is a set of 32 canvases, each bearing an image of a red-and-white can of soup from what company?",
    answer: "Campbell's",
  },
  {
    id: 75,
    category: FOOD_CAT,
    difficulty: 1,
    question:
      "A pestle is one half of a common pair of kitchen utensils used for grinding spices. What is the name of the pestle's bowl-like partner?",
    answer: "Mortar",
  },
  {
    id: 76,
    category: FOOD_CAT,
    difficulty: 1,
    question: "Japanese horseradish is more popularly known as what?",
    answer: "Wasabi",
  },
  {
    id: 77,
    category: FOOD_CAT,
    difficulty: 2,
    question:
      "What is the common name for the food that is technically steamed balls of crushed durum wheat semolina? It originated as a Maghrebi dish served with a stew spooned.",
    answer: "Couscous",
  },
  {
    id: 78,
    category: FOOD_CAT,
    difficulty: 2,
    question: "For what food is the Scoville scale used to measure spiciness?",
    answer: "Chili peppers",
  },
  {
    id: 79,
    category: FOOD_CAT,
    difficulty: 2,
    question:
      "What distilled alcoholic spirit has an English name derived from a diminutive form a foreign word for water? In essence, this means the word can be interpreted as 'little water'.",
    answer: "Vodka",
  },
  {
    id: 80,
    category: FOOD_CAT,
    difficulty: 2,
    question:
      "Dramatically different from today's sweet fruit associated with summertime, what large fruit was cultivated for hundreds of years simply for hydration purposes rather than food?",
    answer: "Watermelon",
  },
  {
    id: 81,
    category: FOOD_CAT,
    difficulty: 2,
    question:
      "If you take a cabbage, cut it finely, and ferment it with various lactic acid bacteria, the output is typically what German side dish?",
    answer: "Sauerkraut",
  },
  {
    id: 82,
    category: FOOD_CAT,
    difficulty: 2,
    question:
      "What staple of Korean cuisine is made from salted and fermented vegetables? The most common ingredients are cabbage and Korean radishes.",
    answer: "Kimchi",
  },
  {
    id: 83,
    category: FOOD_CAT,
    difficulty: 3,
    question:
      "What privately held corporation, founded in 1911 in Tacoma, WA, is a conglomerate that has not only its namesake bars popular around the world, but also “M&M’s”, pet food, and animal care services?",
    answer: "Mars",
  },
  {
    id: 84,
    category: FOOD_CAT,
    difficulty: 3,
    question:
      "As part of a mid-1960s promotion for Toblerone, Swiss chef Conrad Egli invented a chocolate version of what dippy communal dish?",
    answer: "Fondue",
  },
  {
    id: 85,
    category: FOOD_CAT,
    difficulty: 3,
    question:
      "What alcoholic spirit is found in all three of these cocktails: Gimlet, Aviation, and Tom Collins?",
    answer: "Gin",
  },
  {
    id: 86,
    category: FOOD_CAT,
    difficulty: 3,
    question:
      "What Indian spice that usually grows in pods is used to make chai tea?",
    answer: "Cardamom",
  },
];
