
const VANCOUVER_CAT = "Vancouver Landmarks";
const THINGS_CAT = "Things";
const TRICKY_CAT = "Tricky Questions";

export const questions = [
{
    id: 1,
    category: VANCOUVER_CAT,
    difficulty: 1,
    question: "What is this Vancouver landmark?",
    answer: "Canada Place",
    answerImage: "vancouver_landmarks/a-canadap-1.jpg",
    image: "vancouver_landmarks/q-canadap-1.png",
    }
    ,
  {
    id: 2,
    category: VANCOUVER_CAT,
    difficulty: 1,
    question: "What is this Vancouver landmark?",
    answer: "East Van Sign",
    answerImage: "vancouver_landmarks/a-eastvan-1.jpg",
    image: "vancouver_landmarks/q-eastvan-1.png",
  },
  {
    id: 3,
    category: VANCOUVER_CAT,
    difficulty: 1,
    question: "What is this Vancouver landmark?",
    answer: "Arthur Erickson Place",
    answerImage: "vancouver_landmarks/a-macmillan-1.jpg",
    image: "vancouver_landmarks/q-macmillan-1.png",
  },
  {
    id: 4,
    category: VANCOUVER_CAT,
    difficulty: 1,
    question: "What is this Vancouver landmark?",
    answer: "Totem Poles in Stanley Park",
    answerImage: "vancouver_landmarks/a-totem-1.jpg",
    image: "vancouver_landmarks/q-totem-1.png",
  },
  {
    id: 5,
    category: VANCOUVER_CAT,
    difficulty: 2,
    question: "What is this Vancouver landmark?",
    answer: "BC Place",
    answerImage: "vancouver_landmarks/a-bcplace-2.jpg",
    image: "vancouver_landmarks/q-bcplace-2.png",
  },
  {
    id: 6,
    category: VANCOUVER_CAT,
    difficulty: 2,
    question: "What is this Vancouver landmark?",
    answer: "Marine Building",
    answerImage: "vancouver_landmarks/a-marine-2.jpg",
    image: "vancouver_landmarks/q-marine-2.png",
  },
  {
    id: 7,
    category: VANCOUVER_CAT,
    difficulty: 2,
    question: "What is this Vancouver landmark?",
    answer: "SFU Campus",
    answerImage: "vancouver_landmarks/a-sfu-2.jpg",
    image: "vancouver_landmarks/q-sfu-2.png",
  },
  {
    id: 8,
    category: VANCOUVER_CAT,
    difficulty: 2,
    question: "What is this Vancouver landmark?",
    answer: "Vancouver House",
    answerImage: "vancouver_landmarks/a-vhouse-2.jpg",
    image: "vancouver_landmarks/q-vhouse-2.png",
  },
  {
    id: 9,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Burrard Bridge",
    answerImage: "vancouver_landmarks/a-burrard-3.jpg",
    image: "vancouver_landmarks/q-burrard-3.png",
  },
  {
    id: 10,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Steam Clock in Gas Town",
    answerImage: "vancouver_landmarks/a-clock-3.jpg",
    image: "vancouver_landmarks/q-clock-3.png",
  },
  {
    id: 11,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Science World",
    answerImage: "vancouver_landmarks/a-sciencew-3.jpg",
    image: "vancouver_landmarks/q-sciencew-3.png",
  },
  {
    id: 12,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Museum of Anthropology",
    answerImage: "vancouver_landmarks/a-moa-3.jpeg",
    image: "vancouver_landmarks/q-moa-3.png",
  },
  {
    id: 13,
    category: VANCOUVER_CAT,
    difficulty: 3,
    question: "What is this Vancouver landmark?",
    answer: "Sun Tower",
    answerImage: "vancouver_landmarks/a-suntower-3.jpg",
    image: "vancouver_landmarks/q-suntower-3.png",
  },
  {
    id: 14,
    category: THINGS_CAT,
    difficulty: 1,
    question: "What is this thing?",
    answer: "Mushroom",
    answerImage: "things/mushroom-1a.jpg",
    image: "things/mushroom-1q.png",
  },
  {
    id: 15,
    category: THINGS_CAT,
    difficulty: 1,
    question: "What is this thing?",
    answer: "Basketball hoop",
    answerImage: "things/net-1a.jpg",
    image: "things/net-1q.png",
  },
  {
    id: 16,
    category: THINGS_CAT,
    difficulty: 1,
    question: "What is this thing?",
    answer: "Pineapple",
    answerImage: "things/pineapple-1a.jpg",
    image: "things/pineapple-1q.png",
  },
  {
    id: 17,
    category: THINGS_CAT,
    difficulty: 1,
    question: "What is this thing?",
    answer: "Tire",
    answerImage: "things/tire-1a.png",
    image: "things/tire-1q.png",
  },
  {
    id: 18,
    category: THINGS_CAT,
    difficulty: 2,
    question: "What is this thing?",
    answer: "Battery",
    answerImage: "things/battery-2a.jpg",
    image: "things/battery-2q.png",
  },
  {
    id: 19,
    category: THINGS_CAT,
    difficulty: 2,
    question: "What is this thing?",
    answer: "Bowling ball",
    answerImage: "things/bowling-2a.jpg",
    image: "things/bowling-2q.png",
  },
  {
    id: 20,
    category: THINGS_CAT,
    difficulty: 2,
    question: "What is this thing?",
    answer: "$1 Coin",
    answerImage: "things/coin-2a.jpg.webp",
    image: "things/coin-2q.png",
  },
  {
    id: 21,
    category: THINGS_CAT,
    difficulty: 2,
    question: "What is this thing?",
    answer: "Piano",
    answerImage: "things/piano-2a.jpg",
    image: "things/piano-2q.png",
  },
  {
    id: 22,
    category: THINGS_CAT,
    difficulty: 3,
    question: "What is this thing?",
    answer: "Coffee cup",
    answerImage: "things/coffee-3a.jpg",
    image: "things/coffee-3q.png",
  },
  {
    id: 23,
    category: THINGS_CAT,
    difficulty: 3,
    question: "What is this thing?",
    answer: "MacBook or Apple Logo",
    answerImage: "things/macbook-3a.jpg",
    image: "things/macbook-3q.png",
  },
  {
    id: 24,
    category: THINGS_CAT,
    difficulty: 3,
    question: "What is this thing?",
    answer: "Coke can",
    answerImage: "things/coke-3a.png.webp",
    image: "things/coke-3q.png",
  },
  {
    id: 25,
    category: THINGS_CAT,
    difficulty: 3,
    question: "What is this thing?",
    answer: "Dandylion",
    answerImage: "things/dandylion-3a.jpeg",
    image: "things/dandylion-3q.png",
  },
  {
    id: 26,
    category: TRICKY_CAT,
    difficulty: 3,
    question: "What is always in front of you but can't be seen?",
    answer: "The future."
  },
  {
    id: 27,
    category: TRICKY_CAT,
    difficulty: 2,
    question: "What has a neck but no head, two arms but no hands?",
    answer: "A shirt."
  },
  {
    id: 28,
    category: TRICKY_CAT,
    difficulty: 3,
    question: "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?",
    answer: "A pencil."
  },
  {
    id: 29,
    category: TRICKY_CAT,
    difficulty: 3,
    question: "I am light as a feather, yet the strongest one cannot hold me for long. What am I?",
    answer: "Breath."
  },
  {
    id: 30,
    category: TRICKY_CAT,
    difficulty: 1,
    question: "The more you take, the more you leave behind. What am I?",
    answer: "Footsteps."
  },
  {
    id: 31,
    category: TRICKY_CAT,
    difficulty: 1,
    question: "I am always hungry, I must always be fed, the finger I touch, will soon turn red. What am I?",
    answer: "Fire."
  },
  {
    id: 32,
    category: TRICKY_CAT,
    difficulty: 2,
    question: "What has a head and a tail, but no body?",
    answer: "A coin."
  },
  {
    id: 33,
    category: TRICKY_CAT,
    difficulty: 1,
    question: "I am an odd number. Take away a letter and I become even. What number am I?",
    answer: "Seven."
  },
  {
    id: 34,
    category: TRICKY_CAT,
    difficulty: 2,
    question: "I can be cracked, made, told, and played. What am I?",
    answer: "A joke."
  }
  
];